apiVersion: v1
kind: Pod
metadata:
  name: control-3
  labels:
    workload: sleep
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  containers:
  - name: sleep-container
    image: registry.access.redhat.com/ubi8/ubi
    imagePullPolicy: IfNotPresent
    command: ["sleep", "9999999"]
    resources:
      requests:
        cpu: "500m"
  restartPolicy: Never
