apiVersion: v1
kind: Pod
metadata:
  name: control-1-trimaran
  labels:
    workload: make
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  schedulerName: "trimaran-scheduler"
  containers:
  - name: make-container
    image: load-aware/coreutils:deps
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "for i in {1..999}; do echo echo 'making' && make clean && make -j 4; done"]
    resources:
      requests:
        cpu: "100m"
  restartPolicy: Never
